### PR TITLE
Add awx action

### PR DESCRIPTION
**Pull request by Tompage1994**
This PR spins up a full AWX and runs the example yaml playbook against it. 

We could probably refine this a little but I think this is a good start for CI testing

### CODE REVIEW

**Comment by sean-m-sullivan** [comment]
I love it, testing now

**Comment by sean-m-sullivan** [comment]
"msg": "Found too many names Demo Credential at endpoint credentials try using an ID instead of a name",
Failed on Template 2

**Comment by Tompage1994** [comment]
I guess that was the first time seeing the pipeline fail because the playbooks were actually wrong 👍

**Comment by sean-m-sullivan** [comment]
Exactly, Thanks for taking care of it, was going to dive into it this morning.

**Comment by Tompage1994** [comment]
closes #24

**Pull request merged**
